import Link from 'next/link'
import { ArrowRight, HeartHandshake, MapPinned, Wine, BedDouble } from 'lucide-react'
import { hotel, images, rooms } from '@/lib/hotel-data'
import { Header, Footer, MobileActions, Hero, SectionHeading, FeatureCard, RoomCard } from '@/components/hotel-site'

export const metadata = { title: 'Cloud Four Hotel Limited | Hotel & Lounge in Oshodi, Lagos', description: 'Discover Cloud Four Hotel Limited in Mafoluku, Oshodi, Lagos — comfortable accommodation and a stylish lounge experience.' }

export default function Home() {
  return <><Header/><main>
    <Hero eyebrow="Cloud Four Hotel Limited" title={<>Stay Comfortably.<br/><em className="text-gold">Relax Beautifully.</em></>} copy="" image={images.hero}/>
    <section className="bg-ivory px-5 py-20 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2 lg:gap-24"><div className="aspect-[4/5] overflow-hidden"><img src={images.intro} alt="Cloud Four hotel reception" className="h-full w-full object-cover"/></div><div><SectionHeading light eyebrow="Welcome to Cloud Four" title="A Better Way to Stay in Lagos" copy="Welcome to Cloud Four Hotel Limited, a comfortable and stylish hospitality destination in Mafoluku, Oshodi, Lagos. Just 10 minutes from Murtala Muhammed Airport. Whether you're visiting for a short stay, business, relaxation or simply looking for a place to unwind, we give you a welcoming experience from arrival to departure."/><Link href="/rooms" className="dark-button mt-8">Discover Cloud Four <ArrowRight size={16}/></Link></div></div></section>
    <section className="bg-charcoal px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="The Cloud Four difference" title="Designed Around Your Comfort"/><div className="mt-14 grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><FeatureCard icon="BedDouble" title="Comfortable Stay" copy="Thoughtfully presented accommodation designed for a comfortable stay."/><FeatureCard icon="MapPinned" title="Convenient Location" copy="Located 10 minutes from Murtala Muhammed Airport, in Mafoluku."/><FeatureCard icon="Wine" title="Relax & Unwind" copy="A dedicated lounge and bar experience for guests and visitors."/><FeatureCard icon="HeartHandshake" title="Personal Hospitality" copy="A welcoming environment focused on making every stay enjoyable."/></div></div></section>
    <section className="bg-rich px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Accommodation" title="Thoughtfully Designed for Deep Rest" copy="Choose from our available accommodation options and enjoy a comfortable environment designed for rest and relaxation."/><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{rooms.slice(0, 3).map((room, index) => <RoomCard key={room.title} room={room} index={index}/>)}</div><Link href="/rooms" className="light-button mt-10">View all rooms <ArrowRight size={16}/></Link></div></section>
    <section className="bg-ivory px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><SectionHeading light eyebrow="Mafoluku, Oshodi" title="Location map" copy={hotel.address}/><div className="mt-10 overflow-hidden border border-charcoal/10"><iframe title="Cloud Four Hotel location map" src="https://www.openstreetmap.org/export/embed.html?bbox=3.30%2C6.55%2C3.38%2C6.62&layer=mapnik&marker=6.583%2C3.335" className="h-[420px] w-full border-0" loading="lazy"/></div><a href="https://www.openstreetmap.org/?mlat=6.583&mlon=3.335#map=15/6.583/3.335" target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs uppercase tracking-[0.18em] text-charcoal underline">Open larger map</a></div></section>
  </main><Footer/><MobileActions/></>
}
