'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowUpRight, ChevronDown, Menu, X, Phone, MapPin, BedDouble, MapPinned, Wine, HeartHandshake, ArrowRight } from 'lucide-react'
import { hotel, images, phoneHref, reserveHref, rooms } from '@/lib/hotel-data'

export function Logo({ compact = false }: { compact?: boolean }) {
  return <Link href="/" aria-label="Cloud Four Hotel home" className="flex items-center gap-3"><img src={hotel.logo} alt="Cloud Four Hotel Limited logo" className={compact ? 'h-12 w-12 rounded-full object-cover' : 'h-12 w-12 rounded-full object-cover'} /><span className="hidden text-[11px] font-medium uppercase tracking-[0.24em] text-ivory sm:block">Cloud Four<span className="block text-[9px] tracking-[0.32em] text-gold">Hotel Limited</span></span></Link>
}

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-charcoal/80 backdrop-blur-xl transition-colors"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-9 md:flex"><Link className="nav-link" href="/">Home</Link><Link className="nav-link" href="/rooms">Rooms</Link><Link className="nav-link" href="/lounge">Lounge & Bar</Link><a className="nav-link" href="#contact">Contact</a></nav><div className="hidden md:block"><Link href={reserveHref} className="gold-button">Reserve a Room <ArrowUpRight size={15} /></Link></div><button onClick={() => setOpen(!open)} className="text-ivory md:hidden" aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-white/10 bg-charcoal px-5 py-6 md:hidden"><nav className="flex flex-col gap-5"><Link onClick={() => setOpen(false)} href="/" className="mobile-link">Home</Link><Link onClick={() => setOpen(false)} href="/rooms" className="mobile-link">Rooms</Link><Link onClick={() => setOpen(false)} href="/lounge" className="mobile-link">Lounge & Bar</Link><a onClick={() => setOpen(false)} href="#contact" className="mobile-link">Contact</a><a className="gold-button mt-2 justify-center" href={phoneHref(hotel.phones[0])}><Phone size={15} /> Call to Reserve</a></nav></div>}</header>
}

export function Footer() { return <footer id="contact" className="border-t border-white/10 bg-charcoal px-5 pb-24 pt-16 text-ivory md:pb-10 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 md:grid-cols-[1.3fr_1fr_1.3fr_1fr]"><div><Logo /></div><div><p className="eyebrow">Explore</p><div className="mt-5 flex flex-col gap-3 text-sm"><Link href="/">Home</Link><Link href="/rooms">Rooms</Link><Link href="/lounge">Lounge & Bar</Link></div></div><div><p className="eyebrow">Contact</p><p className="mt-5 max-w-[220px] text-sm leading-6 text-muted-ivory">{hotel.address}</p><div className="mt-4 flex flex-col gap-2 text-sm">{hotel.phones.map(p => <a key={p} href={phoneHref(p)} className="hover:text-gold">{p}</a>)}</div></div><div><p className="eyebrow">Stay in touch</p><p className="mt-5 text-sm text-muted-ivory">{hotel.email}</p><div className="mt-5 flex gap-4 text-xs uppercase tracking-[0.12em] text-muted-ivory"><a href="#" aria-label="Instagram">Instagram</a><a href="#" aria-label="Facebook">Facebook</a></div></div></div><div className="mt-16 flex flex-col justify-between gap-4 border-t border-white/10 pt-6 text-xs text-muted-ivory sm:flex-row"><span>© 2026 Cloud Four Hotel Limited. All Rights Reserved. Designed and Developed by Bainaray.</span><span className="flex gap-5"><a href="#">Privacy Policy</a><a href="#">Terms & Conditions</a></span></div></div></footer> }

export function MobileActions() { return <div className="fixed inset-x-0 bottom-0 z-40 flex border-t border-white/10 bg-charcoal/95 p-3 backdrop-blur md:hidden"><a className="flex flex-1 items-center justify-center gap-2 border-r border-white/15 text-xs uppercase tracking-[0.18em] text-ivory" href={phoneHref(hotel.phones[0])}><Phone size={15} className="text-gold"/> Call</a><a className="flex flex-1 items-center justify-center gap-2 text-xs uppercase tracking-[0.18em] text-ivory" href={reserveHref}><BedDouble size={15} className="text-gold"/> Reserve</a></div> }

export function Hero({ eyebrow, title, copy, image, cta = 'Reserve a Room', secondary = 'Explore Rooms' }: { eyebrow: string; title: string; copy: string; image: string; cta?: string; secondary?: string }) { return <section className="relative flex min-h-[720px] items-end overflow-hidden bg-charcoal pt-20"><img src={image} alt="Premium Cloud Four hospitality interior" className="absolute inset-0 h-full w-full object-cover object-[8%_center] lg:object-center"/><div className="absolute inset-0 bg-gradient-to-t from-charcoal via-charcoal/55 to-charcoal/20"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-24 lg:px-8 lg:pb-32"><p className="eyebrow mb-6 animate-rise">{eyebrow}</p><h1 className="max-w-3xl text-balance font-serif text-5xl leading-[1.04] text-ivory animate-rise sm:text-7xl lg:text-8xl">{title}</h1><p className="mt-7 max-w-xl text-base leading-7 text-ivory/75 animate-rise">{copy}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row animate-rise"><Link href={reserveHref} className="gold-button justify-center">{cta} <ArrowUpRight size={16}/></Link><Link href="/rooms" className="outline-button justify-center">{secondary} <ArrowRight size={16}/></Link></div></div><div className="absolute bottom-8 right-6 hidden items-center gap-3 text-[10px] uppercase tracking-[0.3em] text-ivory/60 sm:flex">Scroll to discover <ChevronDown size={15} className="text-gold"/></div></section> }

export function SectionHeading({ eyebrow, title, copy, light = false }: { eyebrow: string; title: string; copy?: string; light?: boolean }) { return <div className={light ? 'text-charcoal' : 'text-ivory'}><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 max-w-2xl text-balance font-serif text-4xl leading-tight sm:text-5xl">{title}</h2>{copy && <p className={light ? 'mt-5 max-w-xl leading-7 text-charcoal/65' : 'mt-5 max-w-xl leading-7 text-muted-ivory'}>{copy}</p>}</div> }

const featureIcons = { BedDouble, MapPinned, Wine, HeartHandshake } as const
export function FeatureCard({ icon, title, copy }: { icon: keyof typeof featureIcons; title: string; copy: string }) { const Icon = featureIcons[icon]; return <div className="border-t border-gold/60 pt-5"><Icon size={21} className="text-gold"/><h3 className="mt-6 font-serif text-2xl text-ivory">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-ivory">{copy}</p></div> }

export function RoomCard({ room, index }: { room: typeof rooms[number]; index: number }) { const gallery = 'gallery' in room && room.gallery ? room.gallery : [room.image]; return <article className="group overflow-hidden bg-rich"><div className="relative aspect-[4/5] overflow-hidden"><div className="flex h-full snap-x snap-mandatory overflow-x-auto overscroll-x-contain scroll-smooth [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" aria-label={`${room.title} image gallery`}>{gallery.map((src, imageIndex) => <div key={src} className="h-full min-w-full snap-center"><img src={src} alt={`${room.title} accommodation view ${imageIndex + 1}`} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div>)}</div><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-charcoal/75 to-transparent"/><span className="absolute bottom-5 left-5 font-mono text-xs tracking-[0.2em] text-gold">0{index + 1}</span>{gallery.length > 1 && <div className="absolute bottom-5 right-5 flex items-center gap-2" aria-label="Swipe for more room images">{gallery.map((src, imageIndex) => <span key={src} className="h-1.5 w-7 rounded-full bg-ivory/70" aria-label={`Image ${imageIndex + 1}`}/>)}</div>}</div><div className="p-6"><h3 className="font-serif text-2xl text-ivory">{room.title}</h3><p className="mt-3 text-sm leading-6 text-muted-ivory">{room.description}</p><Link href="/rooms" className="mt-6 inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-gold">View room <ArrowRight size={15}/></Link></div></article> }

export function ReservationForm() { return <form id="reservation" onSubmit={(e) => e.preventDefault()} className="grid gap-5 md:grid-cols-2"><label className="field">Full Name<input required type="text" placeholder="Your full name"/></label><label className="field">Phone Number<input required type="tel" placeholder="+234"/></label><label className="field">Email<input required type="email" placeholder="you@example.com"/></label><label className="field">Room Type<select defaultValue=""><option value="" disabled>[Select room type]</option>{rooms.map((r, i) => <option key={i}>{r.title}</option>)}</select></label><label className="field">Check-in Date<input type="date"/></label><label className="field">Check-out Date<input type="date"/></label><label className="field">Number of Guests<select defaultValue="1"><option>1</option><option>2</option><option>3+</option></select></label><label className="field md:col-span-2">Message<textarea rows={4} placeholder="Tell us anything we should know"/></label><button className="gold-button justify-center md:col-span-2">Send Reservation Request <ArrowUpRight size={16}/></button><p className="text-xs leading-5 text-muted-ivory md:col-span-2">Prefer to speak with us directly? <a className="text-gold" href={phoneHref(hotel.phones[0])}>{hotel.phones[0]}</a> or <a className="text-gold" href={phoneHref(hotel.phones[1])}>{hotel.phones[1]}</a></p></form> }

export const iconSet = { BedDouble, MapPinned, Wine, HeartHandshake, MapPin }
export { images }
